# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
  workflow_dispatch:
  schedule:
    # every 1 hour
    - cron:  '1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build HTML
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: |
          pip install -q -r requirements.txt
          python run.py
