name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  push:
  workflow_dispatch:
  schedule:
    # every 1 hour
    - cron:  '1 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: browser-actions/setup-chrome@latest
      - run: chrome --version

      - name: Installing and Building
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
        continue-on-error: true
      - run: |
          pip install -q -r requirements.txt
          echo '\n\n'
          python selenium-crawler.py

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: screenshots
          path: |
            ./**/*.png
